import { type ValueOf } from '../interfaces';
export const DEFAULT_VALUES = {
  DEFAULT_PAGE_SIZE: 20,
  DEFAULT_CURRENT_PAGE: 1,
  DEFAULT_SORT: 'id',
  DEFAULT_ORDER: 'DESC',
  DEFAULT_DELIVERY_STATUS: 'CHUA_GIAO_HANG',
  DEFAULT_PAYMENT_STATUS: 'CHUA_THANH_TOAN',
  DEFAULT_DOCUMENT_STATUS: 'CHUA_CHUNG_TU',
  DEFAULT_DELIVERY_DATE: new Date(),
  DEFAULT_PAYMENT_DATE: new Date(),
  DEFAULT_DOCUMENT_DATE: new Date(),
  DEFAULT_SUPPLIER_ID: 1,
  DEFAULT_PURCHASING_OFFICER_ID: 1,
  DEFAULT_PRODUCT_ID: 1,
  DEFAULT_CUSTOMER_ID: 1,
  DEFAULT_QUANTITY: 1,
  DEFAULT_PRICE: 1,
  DEFAULT_TOTAL: 1,
  DEFAULT_NOTE: 'This is a note',
  DEFAULT_ADDRESS: 'This is an address',
  DEFAULT_PHONE: '0123456789',
  DEFAULT_EMAIL: 'email@example.com',
} as const;

export type DefaultValueType = ValueOf<typeof DEFAULT_VALUES>;
